### ISSUE TITLE
Discord Bot Not Submitting API Calls

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/text-to-cad-discord-bot#88]
The Discord bot is failing to submit the API call. I tried it a couple of times. It reacts to the message, but no API calls are listed under my account. The Text-to-CAD UI works fine, so it's something with the Discord bot.

https://discord.com/channels/915388055236509727/1187104536456867960/1208965887466410055

**Comment by jessfraz** [comment]
fixed
